spring:
  datasource:
    password: "liuyihan"
    url: "jdbc:mysql://localhost:3306/myemployees?serverTimezone=UTC"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
mybatis:
  mapper-locations: classpath:mybatis/*.xml