mybatis:
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    url: jdbc:mysql://localhost/myemployees?serverTimezone=UTC
    username: root
    password: liuyihan
logging:
  level:
    com:
      gui: debug